### ISSUE TITLE
Api Ferdium is down

### ISSUE THREAD

**Issue by awilliansd** [ferdium/ferdium-app#2167]
### Your issue

![Image](https://github.com/user-attachments/assets/643a002e-7761-4290-95b8-b54175a1cf50)

![Image](https://github.com/user-attachments/assets/9fab0860-ee02-401d-ae49-daf4161db2a7)

**Comment by Maddremor** [comment]
Yup

![Image](https://github.com/user-attachments/assets/dad1a420-4917-4523-9ada-2b90e4522b26)

**Comment by Sib0t** [comment]
same 

![Image](https://github.com/user-attachments/assets/68abe299-0d64-4c7e-b37b-1e07dc2cfa78)

**Comment by wavi888** [comment]
Same problem here

**Comment by ndpm13** [comment]
same here

**Comment by ichbestimmtnicht** [comment]
PLEASE fix the programming in a way that the app is usable without an online connection. I really like ferdium but this is a dealbreaker for me.

**Comment by kamleshkc2002** [comment]
I think this is related to https://www.cloudflarestatus.com/incidents/25r9t0vz99rp . a bunch of services are affected.

**Comment by FelipeSharkao** [comment]
> PLEASE fix the programming in a way that the app is usable without an online connection. I really like ferdium but this is a dealbreaker for me.

I agree that it should work even if ferdium servers are down. I kinda surprised that it is not

**Comment by tonyrobertcook** [comment]
I am physically disabled and I use Ferdium to communicate, so I actually need it! Are the creators aware?

**Comment by compuguy** [comment]
I believe so. There are open issues here:
https://github.com/ferdium/ferdium-status/issues/362
https://github.com/ferdium/ferdium-status/issues/361

**Comment by procobain** [comment]
I'm tired of this Ferdium.
It's unacceptable that a simple program needs an online API that goes down four times in a year. It would be enough to work offline like so many other similar applications, but it seems that they like you to say "HI" to them before using them...Enough!

**Comment by marcolopes** [comment]
Same here for several hours now!!!
I'm completely dependant on Ferdium :\\\

![Image](https://github.com/user-attachments/assets/1f9eb3c5-352f-450b-b184-0bd2c39f2412)

**Comment by DemonAlone** [comment]
> I'm tired of this Ferdium. It's unacceptable that a simple program needs an online API that goes down four times in a year. It would be enough to work offline like so many other similar applications, but it seems that they like you to say "HI" to them before using them...Enough!

There is no real free alternative, specially multiplatformed. ElectronIm is fine more or less, but pretty limited. Franz and Rambox are fremium. Other apps i tried even worse.

**Comment by marcolopes** [comment]
> I think this is related to https://www.cloudflarestatus.com/incidents/25r9t0vz99rp . a bunch of services are affected.

That was fixed more than 1 hour ago.

**Ferdium is still DOWN**!

**Comment by marcolopes** [comment]
> > I'm tired of this Ferdium. It's unacceptable that a simple program needs an online API that goes down four times in a year. It would be enough to work offline like so many other similar applications, but it seems that they like you to say "HI" to them before using them...Enough!
> 
> There is no real free alternative, specially multiplatformed. ElectronIm is fine more or less, but pretty limited. Franz and Rambox are fremium. Other apps i tried even worse.

Going back to Franz is a NO GO (many problems)

Any feedback from the devs about the reasons of the outage?

**Comment by gaylie** [comment]
> PLEASE fix the programming in a way that the app is usable without an online connection. I really like ferdium but this is a dealbreaker for me.

> I agree that it should work even if ferdium servers are down. I kinda surprised that it is not

Ferdium IS usable without the API. You can Logout in your settings and choose to use Ferdium without an Account, at which point it should load your local services. If you navigate to https://api.ferdium.org/user/account and log in, you can also export your account data with your services to use locally, although I'm not sure anymore where you can to place said exported data.

**Comment by procobain** [comment]
> > I'm tired of this Ferdium. It's unacceptable that a simple program needs an online API that goes down four times in a year. It would be enough to work offline like so many other similar applications, but it seems that they like you to say "HI" to them before using them...Enough!
> 
> There is no real free alternative, specially multiplatformed. ElectronIm is fine more or less, but pretty limited. Franz and Rambox are fremium. Other apps i tried even worse.

E o tal Station? Acabei de instalar aqui pra testar, o último update é de dezembro/24. Ainda usa Electron27, seria um problema? Vou tentar...

**Comment by marcolopes** [comment]
**BACK ONLINE**!

So, what was the cause of this massive outage??

**Comment by awilliansd** [comment]
Back online, thanks

**Comment by nonamethanks** [comment]
> > I'm tired of this Ferdium. It's unacceptable that a simple program needs an online API that goes down four times in a year. It would be enough to work offline like so many other similar applications, but it seems that they like you to say "HI" to them before using them...Enough!
> 
> There is no real free alternative, specially multiplatformed. ElectronIm is fine more or less, but pretty limited. Franz and Rambox are fremium. Other apps i tried even worse.

Rambox is free and this doesn't happen with them. I had to switch to that app because this bug makes ferdium completely unusable for me. It's not open-source, but at least it doesn't break.

**Comment by DemonAlone** [comment]
> > > I'm tired of this Ferdium. It's unacceptable that a simple program needs an online API that goes down four times in a year. It would be enough to work offline like so many other similar applications, but it seems that they like you to say "HI" to them before using them...Enough!
> > 
> > 
> > There is no real free alternative, specially multiplatformed. ElectronIm is fine more or less, but pretty limited. Franz and Rambox are fremium. Other apps i tried even worse.
> 
> Rambox is free and this doesn't happen with them. I had to switch to that app because this bug makes ferdium completely unusable for me. It's not open-source, but at least it doesn't break.

It is not free. Free plan has limitations, the main for me is  starting with Pro "up to 3 active computers". I have three computers and some of them are with doulbe boot. And also I have portable drives. So for me it is useless and the better way is using Web applications.

**Comment by nonamethanks** [comment]
And it happened again today. Guess this is a good time to uninstall and switch to an alternative. 

> It is not free. Free plan has limitations, the main for me is starting with Pro "up to 3 active computers". I have three computers and some of them are with doulbe boot. And also I have portable drives. So for me it is useless and the better way is using Web applications.

I'd rather take an app that works on limited computers than one that doesn't work at all.

**Comment by jimmylad** [comment]
Maybe I'm oversimplifying it but can't we just find the part in the code which relies on the server reply and add a switch which checks for a local cache of the settings instead?

**Comment by ndpm13** [comment]
I don't mean to be *that* guy but you could always use Ferdium without an account or self host the server. I'll leave the compose file I'm using down below.

<img width="1046" height="661" alt="Image" src="https://github.com/user-attachments/assets/ed45b38a-6696-45f1-9237-a17158012b6c" />

```yml
version: "2"
services:
  ferdium-server:
    image: ferdium/ferdium-server:latest
    container_name: ferdium-server
    environment:
      - NODE_ENV=production
      - APP_URL= # URL HERE
      - DB_CONNECTION=sqlite
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD= # STRONG PASSWORD HERE
      - DB_DATABASE=ferdium
      - DB_SSL=false
      - MAIL_CONNECTION=smtp
      - SMTP_HOST=mail.cock.li # you can use another provider
      - SMTP_PORT=587
      - MAIL_SSL=true
      - MAIL_USERNAME= # EMAIL ADDRESS HERE
      - MAIL_PASSWORD= # EMAIL PASSWORD HERE
      - MAIL_SENDER= # EMAIL ADDRESS HERE
      - IS_CREATION_ENABLED=true
      - IS_DASHBOARD_ENABLED=true
      - IS_REGISTRATION_ENABLED=true # you might wanna disable these for personal use
      - CONNECT_WITH_FRANZ=false
      - DATA_DIR=/data
      - JWT_USE_PEM=true
    volumes:
      - ./ferdium-database-vol:/data
      - ./ferdium-recipes-vol:/app/build/recipes
    ports:
      - 3333:3333
    restart: unless-stopped
volumes:
  ferdium-recipes-vol:
  ferdium-database-vol:
```
